services:
  - type: web
    name: diversity-ventures
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: diversity_secret_key_change_this